language: node_js

env:
  global:
    - PROJECT=PotCert
    - OWNER="Harbar-Inbound"
    - SH=bash
    - PACKAGE_VERSION="1.0.*"
  
services:
  - docker

node_js:
  - "14"
before_script:
  - git clone "https://github.com/${OWNER}/${PROJECT}.git"
  - cd $PROJECT
  - ./bootstrap.sh
